import Head from "next/head";
import Link from "next/link";

function Nav() {
  return (
    <nav style={{ background: "#0D1117", borderBottom: "1px solid rgba(255,255,255,0.05)" }}>
      <div style={{ maxWidth: 1100, margin: "0 auto", padding: "0 24px", display: "flex", alignItems: "center", height: 62 }}>
        <Link href="/" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none" }}>
          <div style={{ width: 30, height: 30, background: "#7C3AED", borderRadius: 8, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16 }}>⚖️</div>
          <span style={{ color: "#FFFFFF", fontWeight: 700, fontSize: 17 }}>ContractClear</span>
        </Link>
      </div>
    </nav>
  );
}

function Footer() {
  return (
    <footer style={{ background: "#0D1117", borderTop: "1px solid rgba(255,255,255,0.06)", padding: "24px", textAlign: "center" }}>
      <p style={{ color: "#4B5563", fontSize: 13, margin: "0 0 10px" }}>© 2024 ContractClear</p>
      <div style={{ display: "flex", justifyContent: "center", gap: 24 }}>
        <Link href="/terms" style={{ color: "#7C3AED", fontSize: 12, textDecoration: "none" }}>Terms of Service</Link>
        <Link href="/privacy" style={{ color: "#4B5563", fontSize: 12, textDecoration: "none" }}>Privacy Policy</Link>
      </div>
    </footer>
  );
}

const Section = ({ title, children }) => (
  <div style={{ marginBottom: 36 }}>
    <h2 style={{ fontSize: 18, fontWeight: 600, color: "#0D1117", margin: "0 0 12px", paddingBottom: 10, borderBottom: "1px solid #E2E8F0" }}>{title}</h2>
    <div style={{ fontSize: 15, color: "#374151", lineHeight: 1.8 }}>{children}</div>
  </div>
);

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service — ContractClear</title>
        <meta name="description" content="Terms of Service for ContractClear — AI-powered contract analysis tool." />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>

      <div style={{ fontFamily: "'Inter', sans-serif", minHeight: "100vh", background: "#F8FAFC" }}>
        <Nav />

        <div style={{ maxWidth: 760, margin: "0 auto", padding: "60px 24px 80px" }}>

          {/* Header */}
          <div style={{ marginBottom: 48 }}>
            <p style={{ fontSize: 12, fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase", color: "#7C3AED", margin: "0 0 10px" }}>Legal</p>
            <h1 style={{ fontSize: 36, fontWeight: 700, color: "#0D1117", margin: "0 0 12px", letterSpacing: "-0.02em" }}>Terms of Service</h1>
            <p style={{ fontSize: 14, color: "#6B7280", margin: 0 }}>Last updated: June 2025 · Effective immediately</p>
          </div>

          {/* Highlight box */}
          <div style={{ background: "#F5F3FF", border: "1px solid #DDD6FE", borderRadius: 12, padding: "18px 20px", marginBottom: 40 }}>
            <p style={{ fontSize: 14, color: "#4C1D95", margin: 0, lineHeight: 1.7 }}>
              <strong>Plain-English summary:</strong> ContractClear is a free AI tool that helps you understand contracts. It is not a law firm and does not provide legal advice. By using this tool, you agree to these terms. Always consult a real lawyer before signing important legal documents.
            </p>
          </div>

          <Section title="1. Acceptance of Terms">
            <p>By accessing or using ContractClear ("the Service," "we," "our"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
            <p style={{ marginTop: 12 }}>We reserve the right to update these terms at any time. Continued use of the Service after changes constitutes your acceptance of the revised terms.</p>
          </Section>

          <Section title="2. Description of Service">
            <p>ContractClear is an AI-powered tool that analyzes legal documents and contracts, providing plain-English summaries, highlighting potential red flags, identifying key obligations, and suggesting questions for review. The Service is designed to help non-lawyers better understand legal documents.</p>
            <p style={{ marginTop: 12 }}>The Service is provided free of charge. We reserve the right to introduce paid features or usage limits in the future with reasonable notice.</p>
          </Section>

          <Section title="3. Not Legal Advice — Important Disclaimer">
            <div style={{ background: "#FEF2F2", border: "1px solid #FCA5A5", borderRadius: 10, padding: "16px 18px", marginBottom: 14 }}>
              <p style={{ margin: 0, color: "#991B1B", fontWeight: 500, lineHeight: 1.7 }}>
                ⚠️ ContractClear does NOT provide legal advice. The analysis generated by our tool is for informational and educational purposes only. It does not constitute legal advice, does not create an attorney-client relationship, and should not be relied upon as a substitute for consultation with a qualified legal professional.
              </p>
            </div>
            <p>Always consult a licensed attorney in your jurisdiction before signing, modifying, or acting upon any legal document or contract. Laws and regulations vary significantly by location, and an AI tool cannot replace professional legal judgment.</p>
            <p style={{ marginTop: 12 }}>ContractClear is not responsible for any decisions made, or actions taken, based on the analysis provided by this tool.</p>
          </Section>

          <Section title="4. Acceptable Use">
            <p>You agree to use the Service only for lawful purposes. You must not:</p>
            <ul style={{ paddingLeft: 20, marginTop: 10 }}>
              {[
                "Upload documents that contain malicious code or malware",
                "Use the Service to analyze documents in furtherance of illegal activity",
                "Attempt to reverse-engineer, scrape, or exploit the Service",
                "Misrepresent the AI-generated output as actual legal advice to third parties",
                "Upload documents containing sensitive personal data of others without their consent",
                "Use automated systems to make excessive requests to the Service",
              ].map((item, i) => <li key={i} style={{ marginBottom: 8 }}>{item}</li>)}
            </ul>
          </Section>

          <Section title="5. Intellectual Property">
            <p>The ContractClear name, logo, design, and underlying technology are the intellectual property of ContractClear and its creators. You may not copy, reproduce, or distribute any part of the Service without our prior written permission.</p>
            <p style={{ marginTop: 12 }}>The documents you upload remain your property. By uploading a document, you grant us a temporary, limited license to process it solely for the purpose of generating your analysis. We do not claim ownership of your documents.</p>
          </Section>

          <Section title="6. Data and Privacy">
            <p>We take your privacy seriously. Contract documents submitted to our Service are processed in real time to generate your analysis and are <strong>not stored on our servers</strong>. Please review our <Link href="/privacy" style={{ color: "#7C3AED" }}>Privacy Policy</Link> for full details on how we handle your information.</p>
          </Section>

          <Section title="7. Disclaimer of Warranties">
            <p>The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that:</p>
            <ul style={{ paddingLeft: 20, marginTop: 10 }}>
              {[
                "The analysis will be accurate, complete, or error-free",
                "The Service will be available at all times without interruption",
                "The AI will correctly identify all risks or red flags in a document",
                "The output will be suitable for your specific legal situation",
              ].map((item, i) => <li key={i} style={{ marginBottom: 8 }}>{item}</li>)}
            </ul>
          </Section>

          <Section title="8. Limitation of Liability">
            <p>To the fullest extent permitted by applicable law, ContractClear and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of — or inability to use — the Service, including but not limited to damages resulting from reliance on AI-generated analysis.</p>
            <p style={{ marginTop: 12 }}>Our total liability to you for any claim arising out of or relating to these terms or the Service shall not exceed the amount you paid us in the 12 months preceding the claim (which, for free users, is zero).</p>
          </Section>

          <Section title="9. Third-Party Services">
            <p>ContractClear uses third-party AI infrastructure to process your documents. By using our Service, you acknowledge that your document text may be transmitted to these third-party providers solely for the purpose of generating your analysis, subject to their respective terms and privacy policies.</p>
          </Section>

          <Section title="10. Termination">
            <p>We reserve the right to suspend or terminate access to the Service at any time, with or without notice, for any reason including violation of these Terms. Upon termination, your right to use the Service will immediately cease.</p>
          </Section>

          <Section title="11. Governing Law">
            <p>These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising out of or relating to these Terms shall be subject to the exclusive jurisdiction of the courts located in India.</p>
          </Section>

          <Section title="12. Contact Us">
            <p>If you have any questions about these Terms of Service, please contact us. We aim to respond to all inquiries within 5 business days.</p>
          </Section>

          <div style={{ borderTop: "1px solid #E2E8F0", paddingTop: 24, marginTop: 8 }}>
            <Link href="/" style={{ color: "#7C3AED", fontSize: 14, textDecoration: "none", fontWeight: 500 }}>← Back to ContractClear</Link>
          </div>
        </div>

        <Footer />
      </div>
    </>
  );
}
